// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Lassoort } from "./Lassoort";

/**
 * Eén te toetsen naad.
 */
export type LasInput = { 
/**
 * Vrij te kiezen aanduiding; komt onveranderd in het resultaat terug.
 */
id: string, soort: Lassoort, 
/**
 * Keeldikte `a` van één las (mm).
 */
a_mm: number, 
/**
 * Rekenwaarde van de kracht in de las per eenheidslengte `F_w,Ed`
 * (N/mm) — bij een langslas de schuifstroom `V_z·S/I_y`.
 */
f_w_ed_n_per_mm: number, 
/**
 * Staalsoort van het **zwakste verbonden onderdeel**, zoals "S235".
 * Hieruit volgen `f_u` (EN 1993-1-1 tabel 3.1) en `β_w` (tabel 4.1).
 */
staalsoort: string, };
