// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExposureClass } from "../concrete/ExposureClass";
import type { PlaatWapeningRichting } from "./PlaatWapeningRichting";

/**
 * De aanwezige wapening van een betonwand.
 */
export type PlaatWapeningInvoer = { 
/**
 * Betonstaalsoort, bijvoorbeeld "B500B" — bepaalt f_yk en f_yd.
 */
staalsoort: string, 
/**
 * Wapening in de horizontale modelrichting (x).
 */
horizontaal: PlaatWapeningRichting, 
/**
 * Wapening in de verticale modelrichting (z).
 */
verticaal: PlaatWapeningRichting, 
/**
 * Milieuklasse (tabel 4.1): de enige ingang van tabel 7.1N (NB) voor
 * w_max. Weglaten = scheurwijdte niet getoetst, met reden; er wordt geen
 * klasse aangenomen.
 */
milieuklasse?: ExposureClass, };
