// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NationaleBijlage } from "../norm/NationaleBijlage";
import type { PlaatCombinatie } from "./PlaatCombinatie";
import type { PlaatMateriaalSoort } from "./PlaatMateriaalSoort";

/**
 * Invoer voor de toets van één plaat.
 *
 * `deny_unknown_fields`, net als de staafinvoertypen: een tikfout in een
 * veldnaam hoort geweigerd te worden en niet stil op een standaardwaarde te
 * vallen.
 */
export type PlateCheckInput = { 
/**
 * De nationale bijlage (normnaad); bepaalt γ_M0.
 */
bijlage: NationaleBijlage, 
/**
 * Plaatnummer uit het model; komt onveranderd terug.
 */
plate_id: number, soort: PlaatMateriaalSoort, 
/**
 * De materiaalnaam zoals de app hem herkende: "S355", "C24", "GL28h", …
 */
materiaal: string, 
/**
 * Plaatdikte in mm. Bij staal bepaalt zij de dikteklasse van tabel 3.1.
 */
thickness_mm: number, 
/**
 * Kanttekeningen van de invoerbouwer; rekenen nergens mee en komen
 * letterlijk in de notities van het resultaat.
 */
notities?: Array<string>, 
/**
 * De elementspanningen per UGT-combinatie.
 */
combinations: Array<PlaatCombinatie>, };
