// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NamedValue } from "./NamedValue";

/**
 * Eén stap uit de afleiding die aan een toets voorafgaat.
 *
 * `intermediate_values` op [`StabilityCalc`] draagt alleen de UITKOMSTEN van
 * zo'n keten: een lijstje `S = 2006 mm   C = 4,12`. Waar die getallen vandaan
 * komen staat er niet bij, en een rapport dat een normtoets moet verantwoorden
 * heeft juist dát nodig. Een `Deelstap` draagt daarom de hele stap: de formule
 * symbolisch, dezelfde formule met de getallen ingevuld, de uitkomst met haar
 * eenheid, en de vindplaats in de norm.
 *
 * **Waarom de ingevulde regel uit de rekenkern komt en niet uit de frontend.**
 * De frontend maakt zo'n regel nu door de symbolen in `formula_latex` door hun
 * waarde te vervangen (`vulGetallenIn`). Dat werkt voor een formule als
 * `N_{c,Rd} = A f_y / \gamma_{M0}`, maar de NB-keten bevat wortels met losse
 * hoofdletters (`\sqrt{E I_z / (G I_t)}`) naast samengestelde symbolen, en
 * bovendien eenheidsomrekeningen (kNm → N·mm) die geen symbool hebben. Wie de
 * formule kent kan de ingevulde regel exact opschrijven; een tekstvervanging
 * achteraf kan dat niet. `ingevuld_latex` is daarom hier gevuld. Is hij leeg,
 * dan hoort er geen ingevulde regel te staan (bijvoorbeeld bij een stap die
 * alleen uitgangspunten opsomt).
 */
export type Deelstap = { 
/**
 * Stabiele sleutel, bedoeld om een stap in code of test op terug te vinden
 * (`"m_cr"`, `"k_red"`, `"uitgangspunten"`). Geen rapporttekst.
 */
id: string, 
/**
 * Nederlandse kop boven de stap, bijvoorbeeld "Kritiek kipmoment".
 */
titel: string, 
/**
 * Het LaTeX-symbool van de grootheid die deze stap oplevert (`"M_{cr}"`).
 * Leeg als de stap geen enkele grootheid oplevert.
 */
symbol: string, 
/**
 * De vindplaats: vergelijking- of artikelnummer, bijvoorbeeld `"NB.148"`
 * of `"NB.NB.4.3(3)"`. Apart veld, niet als achtervoegsel in de titel —
 * het rapport zet hem in de rechtermarge.
 */
article: string, 
/**
 * De formule symbolisch.
 */
formula_latex: string, 
/**
 * Dezelfde formule met de getallen ingevuld. Leeg = geen ingevulde regel.
 */
ingevuld_latex: string, 
/**
 * De grootheden die in de formule voorkomen, mét de eenheid waarin ze in
 * díe formule staan (dus N·mm waar de formule N·mm rekent, ook als de
 * uitgangspuntenlijst dezelfde grootheid in kNm toont).
 */
variables: Array<NamedValue>, 
/**
 * De uitkomst van de stap. `None` voor een stap zonder uitkomst.
 */
value: number | null, unit: string, 
/**
 * Kanttekeningen bij déze stap: welke tak van de norm geldt, waar een
 * benadering buiten de norm om is aangehouden, welke aanname eronder ligt.
 */
notes: Array<string>, };
