// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BeamCheckResult } from "./BeamCheckResult";
import type { TimberBeamCheckResult } from "../timber/TimberBeamCheckResult";

export type ReportInput = { project_name: string, project_number: string, engineer: string, company: string, date: string, steel_check_results: Array<BeamCheckResult>, 
/**
 * Houttoetsingen (EN 1995-1-1). `#[serde(default)]` zodat bestaande
 * aanroepen zonder dit veld geldig blijven; in TypeScript daarom
 * optioneel.
 */
timber_check_results?: Array<TimberBeamCheckResult>, };
