// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BeamCheckResult } from "./BeamCheckResult";
import type { ConcreteBeamCheckResult } from "../concrete/ConcreteBeamCheckResult";
import type { TimberBeamCheckResult } from "../timber/TimberBeamCheckResult";

export type ReportInput = { project_name: string, project_number: string, engineer: string, company: string, date: string, steel_check_results: Array<BeamCheckResult>, 
/**
 * Houttoetsingen (EN 1995-1-1). `#[serde(default)]` zodat bestaande
 * aanroepen zonder dit veld geldig blijven; in TypeScript daarom
 * optioneel.
 */
timber_check_results?: Array<TimberBeamCheckResult>, 
/**
 * Betontoetsingen (EN 1992-1-1): buiging met normaalkracht op de
 * doorsnede. `#[serde(default)]` om dezelfde reden als bij hout —
 * bestaande aanroepen zonder dit veld blijven geldig.
 *
 * LET OP bij het lezen van deze resultaten: de betonkern toetst
 * uitsluitend de doorsnede op M en N. Dwarskracht, wringing, pons,
 * scheurwijdte, doorbuiging, tweede-orde-effecten en de
 * detailleringsregels zitten er NIET in; zie het beperkingenblok van de
 * betonsectie in het live rapport.
 *
 * De tweede orde is daarmee niet per se afwezig uit de BEREKENING: het
 * analysetype "2e orde + fysisch" bepaalt de krachtsverdeling met de
 * algemene methode van 5.8.6, via `concrete_check::segments` en de lus in
 * de frontend. Die segmenttabellen, hun convergentiespoor en de
 * verplichte kruipvermelding staan alleen in het LIVE rapport
 * (hoofdstuk "Beton — fysisch niet-lineaire tweede orde"); deze
 * PDF-invoer draagt uitsluitend toetsresultaten en dus geen van beide.
 * Wie ze in de PDF wil hebben, breidt `ReportInput` uit met het
 * `SegmentStiffnessResponse`-spoor per combinatie.
 */
concrete_check_results?: Array<ConcreteBeamCheckResult>, };
