// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NamedCheck } from "../steel/NamedCheck";

/**
 * Antwoord op [`ConcreteColumnCheckRequest`].
 */
export type ConcreteColumnCheckResponse = { beam_id: number, section_name: string, 
/**
 * De toetsen in hetzelfde contract als de rest van de betontoetsing:
 * §5.8.3.1 (de poort), §5.8.4 (kruip) en de §9.5-eisen.
 */
checks: Array<NamedCheck>, 
/**
 * λ = l₀/i. `None` als §5.8 niet van toepassing was of niet kon.
 */
lambda?: number, 
/**
 * λ_lim = 20·A·B·C/√n.
 */
lambda_lim?: number, 
/**
 * l₀ in mm.
 */
l0_mm?: number, 
/**
 * λ < λ_lim: §5.8.3.1(1) staat toe de tweede-orde-effecten te
 * verwaarlozen. `None` = niet vastgesteld.
 */
tweede_orde_verwaarloosbaar?: boolean, 
/**
 * De effectieve kruipcoëfficiënt φ_ef uit (5.19), als hij te bepalen was.
 */
phi_ef?: number, };
