// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DesignSituation } from "./DesignSituation";
import type { ForcePoint } from "../steel/ForcePoint";
import type { ReinforcementCage } from "./ReinforcementCage";
import type { SteelBranch } from "./SteelBranch";

/**
 * Invoer voor één betonnen staaf (rechthoekige doorsnede b × h met korf).
 *
 * `deny_unknown_fields`: een tikfout in een veldnaam met `#[serde(default)]`
 * zou anders stilzwijgend de standaardwaarde opleveren.
 */
export type ConcreteBeamCheckInput = { beam_id: number, 
/**
 * Doorsnedebreedte b in mm.
 */
width_mm: number, 
/**
 * Doorsnedehoogte h in mm (buiging om de sterke as).
 */
height_mm: number, 
/**
 * Betonsterkteklasse, bijv. "C30/37" (tabel 3.1).
 */
concrete_class: string, 
/**
 * Wapeningsstaal, bijv. "B500B" (bijlage C).
 */
reinforcement_grade: string, 
/**
 * Wapeningskorf: dekking, beugel, boven- en onderwapening.
 */
cage: ReinforcementCage, 
/**
 * Staaflengte in m.
 */
length_m: number, 
/**
 * Krachtsverloop (envelop) langs de staaf; N drukt negatief.
 */
forces_envelope: Array<ForcePoint>, 
/**
 * Aantal stroken waarin de doorsnede voor de integratie van de
 * betonspanning wordt verdeeld ("in hoeveel delen opknippen").
 */
n_strips: number, 
/**
 * Bovenste tak van het staaldiagram (3.2.7(2)); standaard horizontaal.
 */
steel_branch: SteelBranch, 
/**
 * Ontwerpsituatie voor tabel 2.1N; standaard blijvend en tijdelijk.
 */
design_situation: DesignSituation, 
/**
 * Minimale excentriciteit e₀ = max(h/30; 20 mm) toepassen bij druk (6.1(4)).
 */
apply_min_eccentricity: boolean, };
