// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConcreteSectionInput } from "./ConcreteSectionInput";
import type { DesignSituation } from "./DesignSituation";
import type { ExposureClass } from "./ExposureClass";
import type { ForcePoint } from "../steel/ForcePoint";
import type { ReinforcementCage } from "./ReinforcementCage";
import type { SteelBranch } from "./SteelBranch";
import type { StructuralSystem } from "./StructuralSystem";

/**
 * Invoer voor één betonnen staaf: een doorsnede met een wapeningskorf.
 *
 * `deny_unknown_fields`: een tikfout in een veldnaam met `#[serde(default)]`
 * zou anders stilzwijgend de standaardwaarde opleveren.
 *
 * De doorsnede staat als één `section`-object in het verzoek en niet meer als
 * een losse breedte en hoogte. Dat is met opzet **geen** uitbreiding met
 * extra optionele velden naast de oude twee: dan zou een T te maken zijn door
 * alleen `h_f_mm` in te vullen en `shape` te vergeten, en zou de doorsnede
 * stilzwijgend een rechthoek blijven. Zie [`ConcreteSectionInput`].
 */
export type ConcreteBeamCheckInput = { beam_id: number, 
/**
 * De doorsnede: rechthoek, T of L, met de maten die bij die vorm horen.
 */
section: ConcreteSectionInput, 
/**
 * Betonsterkteklasse, bijv. "C30/37" (tabel 3.1).
 */
concrete_class: string, 
/**
 * Wapeningsstaal, bijv. "B500B" (bijlage C).
 */
reinforcement_grade: string, 
/**
 * Wapeningskorf: dekking, beugel, boven- en onderwapening.
 */
cage: ReinforcementCage, 
/**
 * Staaflengte in m.
 */
length_m: number, 
/**
 * Krachtsverloop (envelop) langs de staaf; N drukt negatief.
 */
forces_envelope: Array<ForcePoint>, 
/**
 * Aantal stroken waarin de doorsnede voor de integratie van de
 * betonspanning wordt verdeeld ("in hoeveel delen opknippen").
 */
n_strips: number, 
/**
 * Bovenste tak van het staaldiagram (3.2.7(2)); standaard horizontaal.
 */
steel_branch: SteelBranch, 
/**
 * Ontwerpsituatie voor tabel 2.1N; standaard blijvend en tijdelijk.
 */
design_situation: DesignSituation, 
/**
 * Minimale excentriciteit e₀ = max(h/30; 20 mm) toepassen bij druk (6.1(4)).
 */
apply_min_eccentricity: boolean, 
/**
 * Krachtsverloop onder de **frequente** BGT-combinatie, NEN-EN 1990
 * uitdrukking (6.15).
 *
 * De nationale bijlage bij 7.3.1(5) vervangt tabel 7.1N door een tabel
 * waarvan alle drie de kolommen "Frequente belastingscombinatie" heten,
 * waar de EN-tekst de quasi-blijvende combinatie noemt. §7.3 vraagt de
 * staalspanning σ_s in de **gescheurde** doorsnede onder díe combinatie;
 * die is uit de UGT-envelop niet af te leiden. Is deze lijst leeg, dan
 * komen de scheurtoetsen als "niet uitgevoerd" in het rapport, met de
 * reden — er wordt geen UGT-spanning voor in de plaats gezet.
 */
sls_frequent_envelope: Array<ForcePoint>, 
/**
 * Milieuklasse van dit element (tabel 4.1) — de ingang van tabel 7.1N
 * voor w_max. `None` = niet opgegeven; §7.3 kan dan niet.
 */
exposure_class?: ExposureClass, 
/**
 * Grootste nominale korrelafmeting d_g in mm, voor §8.2(2) en §9.2(1)e.
 *
 * `None` = niet opgegeven. De norm kent er **geen** aanbevolen waarde
 * voor — d_g hoort bij de betonspecificatie — dus er wordt er ook geen
 * aangenomen; zie [`nen_en_1992_1_1::detaillering::vrije_staafafstand_8_2`].
 */
aggregate_size_mm?: number, 
/**
 * De regel uit tabel 7.4N voor de slankheidstoets van 7.4.2.
 *
 * `None` = niet opgegeven. Dit is niet uit een raamwerkmodel af te
 * leiden: of een staaf een eindveld, een tussenveld of een uitkraging is
 * hangt van de constructie af en niet van de staaf. Zonder deze keuze
 * blijft 7.4.2 ongetoetst, met de reden in het rapport.
 */
structural_system?: StructuralSystem, 
/**
 * Werkelijke hart-op-hartafstand van de trekstaven in mm, voor (7.11) en
 * tabel 7.3N.
 *
 * `None` = niet opgegeven; de orchestrator leidt hem dan af uit de korf
 * (zuivere meetkunde, één rij, gelijkmatig verdeeld tussen de
 * beugelbenen) en meldt dat in de afleiding.
 */
bar_spacing_mm?: number, };
