// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckStatus } from "../steel/CheckStatus";
import type { InteractionPoint } from "./InteractionPoint";
import type { MnKappaDiagram } from "./MnKappaDiagram";
import type { NamedCheck } from "../steel/NamedCheck";

/**
 * Volledig toetsresultaat van één betonnen staaf.
 */
export type ConcreteBeamCheckResult = { beam_id: number, 
/**
 * Doorsnedenaam, bijv. "300 x 500".
 */
section_name: string, 
/**
 * De aannamen die bij DEZE DOORSNEDEVORM horen, woordelijk uit
 * [`nen_en_1992_1_1::section::ConcreteSection::assumptions`]. Leeg bij een
 * rechthoek.
 *
 * Dezelfde teksten staan óók vooraan in de `notes` van elke toets — daar
 * horen ze, want ze gelden voor die toets. Maar een rapport dat ze per
 * toets herhaalt, laat een lezer twee of drie keer dezelfde alinea zien en
 * maakt niet zichtbaar dát het aannamen zijn. Met dit veld weet het rapport
 * welke notes vormaannamen zijn, en kan het ze één keer tonen. Op tekst
 * matchen zou breken zodra de kern één woord wijzigt.
 *
 * De tekst is de kernbron en mag niet vertaald of geherformuleerd worden:
 * dat een L in dit uniaxiale model exact een T is omdat de zijdelingse
 * kromming VERHINDERD wordt verondersteld, en dat de norm daar geen apart
 * artikel voor geeft, is geen zin die in een tweede versie mag bestaan.
 */
shape_assumptions: Array<string>, 
/**
 * Betonsterkteklasse, bijv. "C30/37".
 */
concrete_class: string, 
/**
 * Wapeningsstaal, bijv. "B500B".
 */
reinforcement_grade: string, 
/**
 * "onder 3Ø16, boven 2Ø12, beugel Ø8, dekking 30 mm".
 */
reinforcement_summary: string, a_s_bottom_mm2: number, a_s_top_mm2: number, 
/**
 * Nuttige hoogte d van de onderwapening, mm.
 */
d_mm: number, 
/**
 * Rekenwaarden waarmee is getoetst.
 */
f_cd_mpa: number, f_yd_mpa: number, checks: Array<NamedCheck>, uc_max: number, status: CheckStatus, governing_check_id: string, 
/**
 * M-κ-diagram bij de normaalkracht van het maatgevende M-N-punt.
 */
mn_kappa: MnKappaDiagram | null, 
/**
 * N-M-interactiediagram (bezwijkomhullende) voor positief en negatief moment.
 */
interaction_positive: Array<InteractionPoint>, interaction_negative: Array<InteractionPoint>, };
