// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConcreteColumnInput } from "./ConcreteColumnInput";
import type { ConcreteSectionInput } from "./ConcreteSectionInput";
import type { DesignSituation } from "./DesignSituation";
import type { ForcePoint } from "../steel/ForcePoint";
import type { ReinforcementCage } from "./ReinforcementCage";
import type { SteelBranch } from "./SteelBranch";

/**
 * Verzoek voor de LOSSE kolomtoets — dezelfde rekengang als in de volledige
 * staaftoetsing, zonder dat daar een hele toetsronde voor nodig is.
 *
 * Bedoeld voor het invoerscherm (λ en λ_lim terwijl je typt, zoals de
 * dekkingstoets van 4.4.1 dat al doet) en voor een client buiten de app.
 */
export type ConcreteColumnCheckRequest = { 
/**
 * Staafnummer; komt onveranderd terug.
 */
beam_id: number, 
/**
 * De doorsnede: rechthoek, T of L.
 */
section: ConcreteSectionInput, concrete_class: string, reinforcement_grade: string, 
/**
 * Wapeningskorf. A_s is hier de SOM van de boven- en de onderrij; wat
 * daar in een kolom aan ontbreekt staat bij [`kolomtoetsen`].
 */
cage: ReinforcementCage, 
/**
 * Vrije lengte l tussen de eindaansluitingen, m (§5.8.3.2(3)).
 */
length_m: number, 
/**
 * De §5.8-gegevens.
 */
column: ConcreteColumnInput, 
/**
 * UGT-krachtsverloop langs de staaf; N drukt negatief. Uit deze reeks
 * komen de maatgevende drukkracht, het bijbehorende eerste-orde-moment en
 * de twee eindmomenten.
 */
forces_envelope: Array<ForcePoint>, 
/**
 * Krachtsverloop onder de QUASI-BLIJVENDE BGT-combinatie (NEN-EN 1990
 * uitdrukking (6.16)) — M₀Eqp uit (5.19). Leeg = niet meegestuurd.
 */
sls_quasi_permanent_envelope: Array<ForcePoint>, design_situation: DesignSituation, steel_branch: SteelBranch, };
