// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Beugelzone } from "./Beugelzone";
import type { Kniklengtekeuze } from "./Kniklengtekeuze";
import type { Overlappingssituatie } from "./Overlappingssituatie";
import type { Schoring } from "./Schoring";

/**
 * De §5.8-gegevens van één staaf: het ontwerpbesluit, de kniklengte en de
 * kruip.
 *
 * # Waarom dit een BLOK is en geen losse velden
 *
 * Schoring zonder kniklengte levert geen λ, en een kniklengte zonder schoring
 * geen λ_lim: (5.15) tegenover (5.16) is een factor twee in l₀, en C = 0,7 is
 * voor een ongeschoord element VOORGESCHREVEN terwijl een geschoorde kolom
 * C > 1,7 mag halen. De twee horen bij elkaar, en een blok dat er is of er
 * niet is, maakt het onmogelijk om er één van in te vullen en de andere te
 * vergeten. Ontbreekt het blok, dan wordt §5.8 niet getoetst en staat de reden
 * in het rapport — er is geen aangenomen schoring en geen aangenomen l₀.
 *
 * # Geschoord is een ONTWERPBESLUIT
 *
 * §5.8.1 definieert het letterlijk als een aanname in de berekening en niet
 * als een eigenschap van de constructie. Een raamwerk mét windverband ziet er
 * in een 2D-model niet anders uit dan hetzelfde raamwerk zonder. Daarom is
 * [`Schoring`] hier verplicht zodra het blok bestaat, en wordt het nergens
 * afgeleid.
 *
 * # Per as
 *
 * Dit blok geldt voor de as waarin dit model rekent: buiging om de y-as, in
 * het vlak van het raamwerk. Een kolom kan in het vlak geschoord zijn en er
 * loodrecht op ongeschoord; die tweede richting bestaat in een 2D-model niet
 * en wordt hier dus ook niet gesuggereerd. Wie de zwakke as nodig heeft,
 * toetst hem in een model van dát vlak.
 */
export type ConcreteColumnInput = { 
/**
 * Geschoord of ongeschoord — het ontwerpbesluit van §5.8.1. Verplicht.
 */
bracing: Schoring, 
/**
 * Hoe l₀ wordt bepaald. Verplicht.
 */
buckling_length: Kniklengtekeuze, 
/**
 * Eindwaarde van de kruipcoëfficiënt φ(∞,t₀) volgens §3.1.4.
 *
 * `None` = niet opgegeven. §3.1.4 wordt in deze app niet gerekend — dat
 * vraagt de relatieve luchtvochtigheid, de fictieve dikte h₀, de
 * cementklasse en de ouderdom t₀ bij eerste belasting, geen van alle
 * invoer van een raamwerkmodel. Zonder φ(∞,t₀) blijft φ_ef onbekend en
 * staat §5.8.3.1(1) A = 0,7 toe; dat is GEEN veilige kant maar de waarde
 * bij φ_ef ≈ 2,14, en dat wordt gemeld.
 */
phi_inf_t0?: number, 
/**
 * De zone waarin de kolomdoorsnede ligt, voor s_cl,tmax (§9.5.3(4)).
 *
 * `None` = niet opgegeven; dan komt s_cl,tmax als "niet uitgevoerd"
 * terug. Er wordt niet stilzwijgend [`Beugelzone::Regulier`] aangehouden:
 * dat is de tak ZONDER de reductiefactor 0,6 en dus de ruimste van de
 * twee.
 */
stirrup_zone?: Beugelzone, 
/**
 * Komen er overlappingslassen voor, en ligt deze doorsnede er ter plaatse
 * van? Bepaalt A_s,max (NB bij §9.5.2(3)).
 *
 * `None` = niet opgegeven; dan komt A_s,max als "niet uitgevoerd" terug.
 * [`Overlappingssituatie::GeenLassen`] geeft 0,08·A_c tegenover 0,04·A_c
 * buiten een las — een factor twee, en de ruimste tak. Aannemen mag dus
 * niet.
 */
lap_situation?: Overlappingssituatie, };
