// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BeamLine } from "./BeamLine";
import type { FlangeGeometry } from "./FlangeGeometry";

/**
 * Eén verzoek om de meewerkende flensbreedte, zoals het over het
 * Tauri-command, de toetsbrug en de MCP-server gaat.
 *
 * `deny_unknown_fields`: een tikfout in `b_i_mm` zou anders een lege lijst
 * opleveren en dus b_eff = b_w, stilzwijgend en aan de andere kant van de
 * werkelijkheid.
 */
export type EffectiveFlangeWidthRequest = { 
/**
 * Vrij te kiezen nummer; komt onveranderd terug. 0 als het niet om een
 * staaf uit een model gaat.
 */
beam_id: number, 
/**
 * De doorgaande liggerlijn waar de staaf deel van is.
 */
line: BeamLine, 
/**
 * De flensmaten van figuur 5.3.
 */
flange: FlangeGeometry, };
