// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BeffDistribution } from "./BeffDistribution";

/**
 * Het antwoord: het staafnummer terug plus de verdeling.
 */
export type EffectiveFlangeWidthResponse = { beam_id: number, distribution: BeffDistribution, };
