// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Eén rij hoofdwapening: aantal staven en diameter.
 */
export type RebarRow = { count: number, diameter_mm: number, };
