// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RebarRow } from "./RebarRow";

/**
 * Wapeningskorf: dekking, beugel, boven- en onderwapening.
 */
export type ReinforcementCage = { 
/**
 * Nominale betondekking c_nom op de beugel, in mm (§4.4.1).
 */
cover_mm: number, 
/**
 * Beugeldiameter in mm (0 = geen beugel; de hoofdwapening ligt dan direct
 * achter de dekking).
 */
stirrup_diameter_mm: number, 
/**
 * Bovenwapening (aan de zijde z = h).
 */
top: RebarRow, 
/**
 * Onderwapening (aan de zijde z = 0).
 */
bottom: RebarRow, };
