// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Constructieklasse S1…S6 (4.4.1.2(5), tabel 4.3N).
 */
export type StructuralClass = "S1" | "S2" | "S3" | "S4" | "S5" | "S6";
