// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CltLayup } from "./CltLayup";
import type { CombinationLoadDuration } from "./CombinationLoadDuration";
import type { ForcePoint } from "../steel/ForcePoint";
import type { LoadDurationClass } from "./LoadDurationClass";
import type { ServiceClass } from "./ServiceClass";

/**
 * Invoer voor één CLT-staaf (plaatstrook).
 *
 * `deny_unknown_fields`, om dezelfde reden als bij
 * [`crate::TimberBeamCheckInput`]: `k_cr` en `load_sharing` hebben een
 * standaardwaarde, en een tikfout in die namen viel stil op die standaard
 * terug (gemeten: `kcr` werd genegeerd).
 */
export type CltBeamCheckInput = { beam_id: number, 
/**
 * Opbouw: breedte van de strook en de lagen van boven naar beneden.
 */
layup: CltLayup, 
/**
 * Klimaatklasse §2.3.1.3.
 */
service_class: ServiceClass, 
/**
 * Belastingduurklasse (§2.3.1.2) voor de hele omhullende, en de terugval
 * voor een combinatie die niet in `load_duration_per_combination` staat.
 * Zonder die lijst geldt deze ene klasse voor ALLE combinaties, en wordt
 * de combinatie met alleen de blijvende belasting dus niet met k_mod
 * "blijvend" getoetst (§3.1.3(2)).
 */
load_duration: LoadDurationClass, 
/**
 * De belastingduurklasse per UGT-combinatie (§3.1.3(2)); leeg = het
 * gedrag van vóór dit veld. Zie `crate::belastingduur`.
 */
load_duration_per_combination?: Array<CombinationLoadDuration>, 
/**
 * Staaflengte in m (voor de slankheidsindicatie L/h).
 */
length_m: number, 
/**
 * Krachtsverloop (envelop) langs de staaf.
 */
forces_envelope: Array<ForcePoint>, 
/**
 * Scheurfactor k_cr (6.13a); NB: 1,0 voor prismatische doorsneden.
 */
k_cr: number, 
/**
 * Lastverdelend systeem aanwezig → k_sys = 1,1 (§6.6).
 */
load_sharing: boolean, };
