// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CltLayup } from "./CltLayup";
import type { ForcePoint } from "../steel/ForcePoint";
import type { LoadDurationClass } from "./LoadDurationClass";
import type { ServiceClass } from "./ServiceClass";

/**
 * Invoer voor één CLT-staaf (plaatstrook).
 */
export type CltBeamCheckInput = { beam_id: number, 
/**
 * Opbouw: breedte van de strook en de lagen van boven naar beneden.
 */
layup: CltLayup, 
/**
 * Klimaatklasse §2.3.1.3.
 */
service_class: ServiceClass, 
/**
 * Maatgevende belastingduurklasse van de UGT-combinatie (§3.1.3).
 */
load_duration: LoadDurationClass, 
/**
 * Staaflengte in m (voor de slankheidsindicatie L/h).
 */
length_m: number, 
/**
 * Krachtsverloop (envelop) langs de staaf.
 */
forces_envelope: Array<ForcePoint>, 
/**
 * Scheurfactor k_cr (6.13a); NB: 1,0 voor prismatische doorsneden.
 */
k_cr: number, 
/**
 * Lastverdelend systeem aanwezig → k_sys = 1,1 (§6.6).
 */
load_sharing: boolean, };
