// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CltLayerOrientation } from "./CltLayerOrientation";

/**
 * Eén lamel (laag) van de opbouw.
 */
export type CltLayer = { 
/**
 * Laagdikte in mm.
 */
thickness_mm: number, orientation: CltLayerOrientation, 
/**
 * Sterkteklasse van de lamellen in deze laag, bijv. "C24" (EN 338).
 */
strength_class: string, };
