// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomSection } from "../steel/CustomSection";
import type { ForcePoint } from "../steel/ForcePoint";
import type { LateralBracing } from "../steel/LateralBracing";
import type { LoadDurationClass } from "./LoadDurationClass";
import type { LtbLoadCase } from "./LtbLoadCase";
import type { LtbLoadPosition } from "./LtbLoadPosition";
import type { ServiceClass } from "./ServiceClass";

/**
 * Invoer voor één houten staaf (rechthoekige doorsnede b × h).
 *
 * `deny_unknown_fields`: een onbekend veld is een FOUT en geen ruis. Zeventien
 * velden hieronder hebben een standaardwaarde, en zonder deze regel viel een
 * tikfout in zo'n veldnaam stil terug op die standaard. Gemeten: `kcr` in
 * plaats van `k_cr` gaf dwarskracht-UC 1,066 in plaats van 1,591, en
 * `deflection_quasi_perm_m` liet de kruipterm k_def·w_qp van §7.2 wegvallen
 * (w_fin-UC 0,788 in plaats van 1,143) — beide zonder melding. Staal
 * (`BeamCheckInput`) en beton (`ConcreteBeamCheckInput`) weigerden al.
 */
export type TimberBeamCheckInput = { beam_id: number, 
/**
 * Doorsnedebreedte b in mm. Bij een samengestelde doorsnede
 * (`custom_section`) de omhullende breedte; de toetsing rekent dan met
 * de grootheden uit die doorsnede en niet met b x h.
 */
width_mm: number, 
/**
 * Doorsnedehoogte h in mm (buiging om de sterke as).
 */
height_mm: number, 
/**
 * Een samengestelde doorsnede uit de profieleditor, als lamellen.
 *
 * WAAROM DIT VELD ER IS
 * Zonder dit veld kan alleen een rechthoek b x h worden getoetst, en dat
 * is niet alleen een gemis maar een gevaar. Wie een samengestelde ligger
 * (flenzen 1000 x 40, lijf 71 x 40, h = 120) als "1000x120" invoert,
 * krijgt bij de dwarskrachttoets van art. 6.1.7 een schuifspanning die
 * ruim een orde van grootte te laag is: die toets hoort met de breedte
 * van het LIJF en met de eigen S en I te rekenen, niet met b x h.
 *
 * De grootheden worden uit de lamellen berekend door `section-properties`
 * -- dezelfde motor die de profieleditor gebruikt -- inclusief de
 * maatgevende schuifvezel. Zit er geen lamel in (een catalogusdeel, of
 * alleen kant-en-klare eigenschappen), dan is er geen contour om een
 * breedte op te meten en weigert de toetsing met een melding.
 *
 * Weglaten = rechthoek b x h, precies zoals voorheen. `#[ts(optional)]`
 * zodat het veld ook in TypeScript weglaatbaar is en de bestaande
 * bouwers ongewijzigd blijven compileren -- dezelfde afspraak als bij
 * `BeamCheckInput::custom_section` van de staaltoetsing.
 */
custom_section?: CustomSection, 
/**
 * Sterkteklasse, bijv. "C24" (EN 338) of "GL28h" (EN 14080).
 */
strength_class: string, 
/**
 * Klimaatklasse (service class) §2.3.1.3.
 */
service_class: ServiceClass, 
/**
 * Maatgevende belastingduurklasse van de UGT-combinatie (§3.1.3:
 * de kortst durende belasting in de combinatie bepaalt k_mod).
 */
load_duration: LoadDurationClass, 
/**
 * Staaflengte in m.
 */
length_m: number, 
/**
 * Krachtsverloop (envelop) langs de staaf; N drukt negatief.
 */
forces_envelope: Array<ForcePoint>, 
/**
 * Kniklengte om de sterke y-as (m) — knik IN het vlak van het model.
 *
 * `0` of weglaten = niet opgegeven: de kern houdt de staaflengte aan en
 * zegt dat in de afleiding ("staaflengte (terugval)"). Negatief of niet
 * eindig wordt genegeerd mét een kanttekening.
 */
buckling_length_y_m: number, 
/**
 * Kniklengte om de zwakke z-as (m) — knik UIT het vlak van het model.
 *
 * `0` of weglaten = niet opgegeven. De kern leidt L_cr,z dan af uit
 * [`Self::lateral_bracing`], maar alleen op plaatsen waar een steun aan
 * de boven- ÉN aan de onderrand zit; anders geldt de staaflengte. De
 * gebruikte waarde en haar herkomst staan in de kolomtoets en in de
 * drukterm van de kiptoets.
 */
buckling_length_z_m: number, 
/**
 * Zijdelingse steunen als fracties van de staaflengte, per rand — dezelfde
 * vorm als bij staal (`top_flange_positions` = bovenrand,
 * `bottom_flange_positions` = onderrand).
 *
 * ALLEEN voor de kniklengte om de z-as. De kiptoets van art. 6.3.3 rekent
 * met zijn eigen [`Self::ltb_segment_length_m`] en leidt niets uit deze
 * posities af; dat besluit is bewust en blijft staan (zie de toelichting
 * bij dat veld in de invoerbouwer).
 *
 * Weglaten = geen steunen, dus geen afleiding.
 */
lateral_bracing?: LateralBracing, 
/**
 * Kipsteunafstand (m) voor tabel 6.1; 0 → staaflengte.
 */
ltb_segment_length_m: number, 
/**
 * Belastinggeval voor l_ef (tabel 6.1).
 */
ltb_load_case: LtbLoadCase, 
/**
 * Aangrijpingspunt van de belasting (tabel 6.1, voetnoot).
 */
ltb_load_position: LtbLoadPosition, 
/**
 * Expliciete effectieve kiplengte in m; 0 → berekenen via tabel 6.1.
 */
ltb_effective_length_override_m: number, 
/**
 * Kiptoets §6.3.3 uitvoeren. De referentie-uitwerking voert 6.3.3
 * alleen voor de ligger uit, niet voor de kolommen.
 */
perform_ltb_check: boolean, 
/**
 * Scheurfactor k_cr voor dwarskracht (6.13a). 1,0 conform de
 * referentie-uitwerking; A1-aanbevolen waarde 0,67.
 */
k_cr: number, 
/**
 * Lastverdelend systeem aanwezig → k_sys = 1,1 (§6.6).
 */
load_sharing: boolean, 
/**
 * Zakking onder de karakteristieke BGT-combinatie (mm, negatief = omlaag).
 */
deflection_inst_mm: number, 
/**
 * Zakking onder de quasi-blijvende BGT-combinatie (mm).
 */
deflection_quasi_perm_mm: number, 
/**
 * Zakking onder de blijvende BGT-combinatie (mm).
 */
deflection_permanent_mm: number, 
/**
 * Noemer voor w_fin (L/n), NB-standaard 250.
 */
deflection_limit_fin: number, 
/**
 * Noemer voor w_add (L/n), NB-standaard 333.
 */
deflection_limit_add: number, 
/**
 * Vrije toelichtingen bij de doorbuigingstoets, die letterlijk in de
 * `notes` van de w_fin-regel van het rapport belanden.
 *
 * Waarom dit bestaat: `deflection_quasi_perm_mm` is een kaal getal, en de
 * kern kan niet zien uit welke belastingscombinatie het komt. De bouwer
 * die de invoer samenstelt weet dat wél — of hij weet juist dat hij de
 * quasi-blijvende combinatie NIET heeft kunnen vinden en op de volle last
 * is teruggevallen. Zonder dit kanaal zou zo'n terugval onzichtbaar zijn,
 * en een onzichtbare aanname is geen aanname maar een fout in wording.
 */
deflection_notes: Array<string>, 
/**
 * Toelichtingen bij de STAAF ALS GEHEEL, letterlijk bij de kolomtoets
 * (art. 6.3.2), de kiptoets (art. 6.3.3) en de eindzakking gezet; rekenen
 * nergens mee. De bouwer zet hier wat hij van de staaf weet en de kern
 * niet: dat een door tussenknopen geknipte staaf als één doorgaande lijn
 * is getoetst, over welke lengte, en welke tussenknopen niet als steun
 * tellen. `None` of leeg = niets te melden.
 */
staaf_notities?: Array<string>, };
